In [65]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris


In [66]:
iris = load_iris()
data = pd.DataFrame(iris.data, columns=iris.feature_names)

In [76]:
data.iloc[:,1:-1].values
X = data.values  
K = 3

In [77]:
n= data.shape[0]
m = data.shape[1]
k = n*m
n

150

In [69]:
# Use the full iris dataset for K-means clustering
X = data.values
# Show first two samples as example
a = X[0]
b = X[1]
c = X[2]
a, b, c

(array([5.1, 3.5, 1.4, 0.2]),
 array([4.9, 3. , 1.4, 0.2]),
 array([4.7, 3.2, 1.3, 0.2]))

In [70]:
def calc_distance(x1,x2):
    # handle 1D numeric vectors: sum over all elements
    return np.sqrt(np.sum((x1 - x2) ** 2))

In [71]:
# compute distance between the two sampled rows
calc_distance(X[0], X[1])

np.float64(0.5385164807134502)

In [72]:
# choose two random indices from X safely
np.random.choice(len(X), size=2, replace=False)

array([124,  22], dtype=int32)

In [73]:
# pick k unique random indices for initial centroids
random_index = np.random.choice(len(X),k)
centroids = X[random_index]

In [74]:
distance0 = []
distance1 = []
distance2 = []

for i in range(n):
    dist = calc_distance(X[i], centroids[0])
    distance0.append(dist)
    
for i in range(n):
    dist = calc_distance(X[i], centroids[1])
    distance1.append(dist)

for i in range(n):
    dist = calc_distance(X[i], centroids[2])
    distance2.append(dist)

In [78]:
labels = []
for i in range(n):
    labels.append(np.argmin([distance0[i], distance1[i], distance2[i]]))

In [79]:
for i in range(n):
    print(np.argmin((distance0[0], distance1[0], distance2[0])))

2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
