In [116]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris


In [117]:
iris = load_iris()
data = pd.DataFrame(iris.data, columns=iris.feature_names)

In [118]:
data.iloc[:,1:-1].values
X

array([[6.1, 2.8, 4.7, 1.2],
       [5.7, 3.8, 1.7, 0.3]])

In [119]:
k = 3
n = 150

In [120]:
# select two random iris samples as numeric arrays
X = data.sample(n=2, random_state=42).values
a = X[0]
b = X[1]
a, b


(array([6.1, 2.8, 4.7, 1.2]), array([5.7, 3.8, 1.7, 0.3]))

In [121]:
def calc_distance(x1,x2):
    # handle 1D numeric vectors: sum over all elements
    return np.sqrt(np.sum((x1 - x2) ** 2))

In [122]:
# compute distance between the two sampled rows
calc_distance(X[0], X[1])

np.float64(3.312099032335839)

In [123]:
# choose two random indices from X safely
np.random.choice(len(X), size=2, replace=False)

array([1, 0], dtype=int32)

In [124]:
# pick k unique random indices for initial centroids
random_index = np.random.choice(len(X),k)
centroids = X[random_index]

In [ ]:
distance0 = []
distance1 = []
distance2 = []

for i in range(n):
    dist = calc_distance(X[i], centroids[0])
    distance0.append(dist)
    
for i in range(n):
    dist = calc_distance(X[i], centroids[1])
    distance1.append(dist)

for i in range(n):
    dist = calc_distance(X[i], centroids[1])
    distance2.append(dist)

IndexError: index 2 is out of bounds for axis 0 with size 2

In [ ]:
for i in range()n:
    print(np.argmin((distance0[0], distance1[0], distance2[0])))

IndexError: list index out of range